[env:t-can485]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = /dev/cu.wchusbserial596F0567951
monitor_port = /dev/cu.wchusbserial596F0567951

lib_deps =
    4-20ma/ModbusMaster@^2.0.1

build_flags =
    -DARDUINO_USB_MODE=1
